name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  pr:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Cache ripgrep binary
        id: cache-ripgrep
        uses: actions/cache@v3
        env:
          cache-name: cache-ripgrep
        with:
          path: |
            .cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: npm ci
        run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'
        env:
          XDG_CACHE_HOME: .cache
      - run: npm run postinstall
        env:
          XDG_CACHE_HOME: .cache
      - run: npm test
      - name: Build
        run: node scripts/build.js
